"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Local data for diagram layouts
 */
exports.data = [
    {
        'Id': 30, 
        'Name': 'Ishaar Das (1931-1996)', 
        'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Saroj Devi',
        'SpouseCity': 'Saharanpur',
        'SpouseBirthDate': '*',
        'MarriageDate': '25-12-1963',
        'BirthDate': '01-03-1931',
        'DeathDate': '13-04-1996',
        'Description': 'First marriage with Shrimati Laxmi Devi ji from Umarpur. And She left this world on 25-12-1963. Second marriage with Shrimati Saroj Devi from Saharanpur in 1964',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0'
    },
    {
        'Id': 31, 'Name': 'Vinod Kumar Singhal', 
        'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Veena Rani',
        'SpouseCity': 'Delhi',
        'SpouseBirthDate': '10-10-1954',
        'MarriageDate': '26-11-1970',
        'JamanTithi': '02-12-1951',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ReportingPerson':30
    },
    {
        'Id': 32, 'Name': 'Vinay Singhal', 'Designation': 'IBM Risk Manager',
        'isMarried': true,
        'MarriedTo': 'Renu Rani',
        'SpouseCity': 'Saharanpur',
        'SpouseBirthDate': '24-05-1977',
        'MarriageDate': '28-01-1999',
        'BirthDate': '01-10-1972',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 31
    },
    {
        'Id': 33, 'Name': 'Vineet Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ReportingPerson': 31
    },
    {
        'Id': 34, 'Name': 'Vipin Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ReportingPerson': 31
    },
    {
        'Id': 35, 'Name': 'Princy Singhal', 'Designation': 'Homemaker',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 31
    },
    {
        'Id': 61, 'Name': 'Praveen Kumar Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ReportingPerson': 30
    },
    {
        'Id': 62, 'Name': 'Naval Singhal', 
        'Designation': 'Businessman - MP',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 61
    },
    {
        'Id': 63, 'Name': 'Rinkal Dev', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ReportingPerson': 61
    },
    {
        'Id': 64, 'Name': 'Ankit Singhal', 'Designation': 'Indian Army :)',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ReportingPerson': 61
    },
    {
        'Id':65, 'Name': 'Amit Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ReportingPerson': 61
    },
    {
        'Id':66, 'Name': 'Sumit Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ReportingPerson': 61
    },
    {
        'Id': 67, 'Name': 'Shipra Singhal', 'Designation': 'Homemaker',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 61
    },
    {
        'Id': 101, 'Name': 'Pushottam Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 30
    },
    {
        'Id': 162, 'Name': 'Ankur Singhal', 'Designation': 'Techno Functional Manager',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 101
    },
    {
        'Id': 163, 'Name': 'Shradha Gupta', 'Designation': 'Homemaker',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 101
    },
    {
        'Id': 164, 'Name': 'Sakshi Singhal', 'Designation': 'Homemaker',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 101
    },
    {
        'Id': 131, 'Name': 'Pawan Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 30
    },
    {
        'Id': 132, 'Name': 'Rahul Singhal', 'Designation': 'Techno Functional Manager',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 131
    },
    {
        'Id': 133, 'Name': 'Vipul Singhal', 'Designation': 'Techno Functional Manager',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 131
    },
    {
        'Id': 134, 'Name': 'Vibhore Singhal', 'Designation': 'Software Engineer',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 131
    },
    {
        'Id': 135, 'Name': 'Akansha Singhal', 'Designation': 'Software Engineer',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 131
    },
    {
        'Id': 161, 'Name': 'Yogesh Kumar Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 30
    },
    {
        'Id': 162, 'Name': 'Arpit Singhal', 'Designation': 'Techno Functional Engineer',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 161
    },
    {
        'Id': 163, 'Name': 'Ayush Singhal', 'Designation': 'Software Engineer',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 161
    },
    {
        'Id': 164, 'Name': 'Achin Singhal', 'Designation': 'Software Engineer',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 161
    },
    {
        'Id': 191, 'Name': 'Mukesh Kumar Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 30
    },
    {
        'Id': 192, 'Name': 'Divik Singhal', 'Designation': 'Software Analyst',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 191
    },
    {
        'Id': 193, 'Name': 'Deepanshi Singhal', 'Designation': 'Manager',
        'isMarried': false,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 191
    },
    {
        'Id': 221, 'Name': 'Brij Mohan', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 30
    },
    {
        'Id': 222, 'Name': 'Vishu Singhal', 'Designation': 'Housewife',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 221
    },
    {
        'Id': 223, 'Name': 'Vibhuti Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 221
    },
    {
        'Id': 224, 'Name': '*Chini', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 221
    },
    {
        'Id': 225, 'Name': 'Sanskar Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 221
    },
    {
        'Id': 251, 'Name': 'Komal Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 30
    },
    {
        'Id': 252, 'Name': 'Vikas Singhal', 'Designation': 'Software Engineer',
        'isMarried': false,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 251
    },
    {
        'Id': 253, 'Name': 'Ashish Singhal', 'Designation': 'Businessman',
        'isMarried': false,
        'MarriedTo': '*',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ReportingPerson': 251
    },
];
