"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ish = [
    {
        'Id': 30, 
        'Name': 'Ishaar Das (1931-1996)', 
        'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Saroj Devi',
        'SpouseCity': 'Saharanpur',
        'SpouseBirthDate': '',
        'MarriageDate': '25-12-1963',
        'BirthDate': '01-03-1931',
        'DeathDate': '13-04-1996',
        'Description': 'First marriage with Shrimati Laxmi Devi ji from Umarpur. And She left this world on 25-12-1963. Second marriage with Shrimati Saroj Devi from Saharanpur in 1964',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0'
    },
    {
        'Id': 31, 'Name': 'Vinod Kumar Singhal', 
        'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Veena Rani',
        'SpouseCity': 'Delhi',
        'SpouseBirthDate': '10-10-1954',
        'MarriageDate': '26-11-1970',
        'JamanTithi': '02-12-1951',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ParentId':30
    },
    {
        'Id': 61, 'Name': 'Praveen Kumar Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Urmila Devi',
        'SpouseCity': 'Muzaffarnagar',
        'SpouseBirthDate': '',
        'MarriageDate': '25-06-1972',
        'BirthDate': '1952',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ParentId': 30
    },
    {
        'Id': 101, 'Name': 'Purshottam Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Alka Rani',
        'SpouseCity': 'Muzaffarnagar',
        'SpouseBirthDate': '',
        'MarriageDate': '22-11-1978',
        'BirthDate': '01-04-1956',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 30
    },
    {
        'Id': 131, 'Name': 'Pawan Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Anita Rani',
        'SpouseCity': 'Agarwal Mandi Tatihri (Baghpat)',
        'SpouseBirthDate': '',
        'MarriageDate': '24-05-1982',
        'BirthDate': '18-06-1958',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 30
    },
    {
        'Id': 161, 'Name': 'Yogesh Kumar Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Chhaya Rani',
        'SpouseCity': 'Agra',
        'SpouseBirthDate': '03-09-1966',
        'MarriageDate': '29-04-1984',
        'BirthDate': '21-09-1960',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 30
    },
    {
        'Id': 191, 'Name': 'Mukesh Kumar Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Anshula Rani',
        'SpouseCity': 'Muzaffarnagar',
        'SpouseBirthDate': '25-07-1966',
        'MarriageDate': '03-07-1988',
        'BirthDate': '14-11-1962',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 30
    },
    {
        'Id': 221, 'Name': 'Brij Mohan', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Vandana Rani',
        'SpouseCity': 'Muzaffarnagar',
        'SpouseBirthDate': '',
        'MarriageDate': '01-07-1987',
        'BirthDate': '19-01-1966',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 30
    },
    {
        'Id': 251, 'Name': 'Komal Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Kavita Rani',
        'SpouseCity': 'Budhana',
        'SpouseBirthDate': '',
        'MarriageDate': '18-02-1991',
        'BirthDate': '14-08-1968',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 30
    },
];
