"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pra = [
    {
        'Id': 62, 'Name': 'Naval Singhal', 
        'Designation': 'Businessman - MP',
        'isMarried': true,
        'MarriedTo': 'Ritu Singhal',
        'SpouseCity': 'Purbaliyan',
        'SpouseBirthDate': '09-06-197*',
        'MarriageDate': '06-05-1996',
        'BirthDate': '07-06-1973',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 61
    },
    {
        'Id': 63, 'Name': 'Rinkal Dev', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Aradana Singhal',
        'SpouseCity': 'Delhi',
        'SpouseBirthDate': '16-09-1974',
        'MarriageDate': '',
        'BirthDate': '07-05-1974',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ParentId': 61
    },
    {
        'Id':64, 'Name': 'Amit Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Sunita Singhal',
        'SpouseCity': 'Delhi',
        'SpouseBirthDate': '12-02-1976',
        'MarriageDate': '15-04-2001',
        'BirthDate': '16-02-1976',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ParentId': 61
    },
    {
        'Id':65, 'Name': 'Sumit Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Parul Singhal',
        'SpouseCity': 'Muzaffarnagar',
        'SpouseBirthDate': '27-09-1974',
        'MarriageDate': '11-12-2005',
        'BirthDate': '18-04-1978',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ParentId': 61
    },
    {
        'Id': 66, 'Name': 'Ankit Singhal', 'Designation': 'Indian Army',
        'isMarried': true,
        'MarriedTo': 'Rashi Singhal',
        'SpouseCity': 'Dehradun',
        'SpouseBirthDate': '09-06-1982',
        'MarriageDate': '16-02-2010',
        'BirthDate': '21-10-1981',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ParentId': 61
    },
    {
        'Id': 67, 'Name': 'Shipra Mittal', 'Designation': 'Homemaker',
        'isMarried': true,
        'MarriedTo': 'Vineet Mittal - Teek Ply and Wood',
        'SpouseCity': 'Chilkana',
        'SpouseBirthDate': '',
        'MarriageDate': '10-12-2003',
        'BirthDate': '25-01-1983',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 61
    },
    {
        'Id': 68, 'Name': 'Akriti Singhal', 'Designation': 'Manager',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '03-04-1997',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 62
    },
    {
        'Id': 69, 'Name': 'Stuti Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '25-06-1999',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 62
    },
    {
        'Id': 70, 'Name': 'Saksham Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '15-09-2000',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 62
    },
    {
        'Id': 71, 'Name': 'Charvi Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '26-04-2006',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 64
    },
    {
        'Id': 72, 'Name': 'Janisha Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '08-04-2010',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 64
    },
    {
        'Id': 73, 'Name': 'Atharva Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '30-03-2008',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 65
    },
    {
        'Id': 74, 'Name': 'Aarna Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '17-02-2013',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 65
    },
    {
        'Id': 75, 'Name': 'Aarya Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '27-08-2012',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 66
    },
    {
        'Id': 76, 'Name': 'Navya Mittal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '**-**-****',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 67
    },
    {
        'Id': 77, 'Name': 'Kanhiya Mittal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '**-**-****',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 67
    },
];
