"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.vin = [
    {
        'Id': 32, 'Name': 'Vinay Singhal', 'Designation': 'IBM Risk Manager',
        'isMarried': true,
        'MarriedTo': 'Renu Singhal',
        'SpouseCity': 'Saharanpur',
        'SpouseBirthDate': '24-05-1977',
        'MarriageDate': '28-01-1999',
        'BirthDate': '01-10-1972',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 31
    },
    {
        'Id': 33, 'Name': 'Vineet Singhal (1973-2008)', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Ruchi Singhal',
        'SpouseCity': 'Gola Gokharnath',
        'SpouseBirthDate': '05-08-1978',
        'MarriageDate': '23-04-2000',
        'BirthDate': '25-11-1973',
        'DeathDate': '26-02-2008',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#68C2DE', 'ParentId': 31
    },
    {
        'Id': 34, 'Name': 'Vipin Singhal', 'Designation': 'Businessman',
        'isMarried': true,
        'MarriedTo': 'Pooja Singhal',
        'SpouseCity': 'Hardoi',
        'SpouseBirthDate': '12-11-1978',
        'MarriageDate': '13-12-2001',
        'BirthDate': '23-08-1975',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'true',
        'RatingColor': '#D46E89', 'ParentId': 31
    },
    {
        'Id': 35, 'Name': 'Princy Singhal', 'Designation': 'Homemaker',
        'isMarried': true,
        'MarriedTo': 'Paresh Mittal',
        'SpouseCity': 'Pilibhit',
        'SpouseBirthDate': '07-01-1974',
        'MarriageDate': '04-12-1998',
        'BirthDate': '12-06-1977',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 31
    },
    {
        'Id': 36, 'Name': 'Ananya Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '25-12-1999',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 32
    },
    {
        'Id': 37, 'Name': 'Arnika Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '30-04-2005',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 32
    },
    {
        'Id': 38, 'Name': 'Taruni Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '11-05-2001',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 33
    },
    {
        'Id': 39, 'Name': 'Pratyaksh Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '15-02-2003',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 33
    },
    {
        'Id': 40, 'Name': 'Vaani Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '28-05-2004',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 33
    },
    {
        'Id': 41, 'Name': 'Kushagra Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '01-03-2003',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 34
    },
    {
        'Id': 42, 'Name': 'Vinamra Singhal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '08-04-2009',
        'Description': '',
        'ImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREmFx6Ff6QaAYkenrTeT5v29yCVjycSXOxkfU-mh9tRJoxMfd0', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 34
    },
    {
        'Id': 43, 'Name': 'Smriti Mittal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '31-12-2000',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 35
    },
    {
        'Id': 44, 'Name': 'Parnika Mittal', 'Designation': 'Student',
        'isMarried': false,
        'MarriedTo': '',
        'SpouseCity': '',
        'SpouseBirthDate': '',
        'MarriageDate': '',
        'BirthDate': '**-**-2003',
        'Description': '',
        'ImageUrl': 'https://cdn2.iconfinder.com/data/icons/business-and-finance-related-hand-gestures/256/face_female_blank_user_avatar_mannequin-512.png', 'IsExpand': 'false',
        'RatingColor': '#93B85A', 'ParentId': 35
    },

];
